import 'package:flutter/material.dart';

const kFF46D1B8 = Color(0xFF46D1B8);
const kFF3D3D3D = Color(0xFF3D3D3D);
const kWhiteColor = Color(0xFFFFFFFF);
const kBlackColor = Color(0xFF000000);
const kFF5E5E5E = Color(0xFF5E5E5E);
const kFF888888 = Color(0xFF888888);
const kFF282828 = Color(0xFF282828);
const kFF4ECEAF = Color(0xFF4ECEAF);
const kFF63DFC1 = Color(0xFF63DFC1);
const kFFA7E9DA = Color(0xFFA7E9DA);
const kFFE8FAF6 = Color(0xFFE8FAF6);
const kFFE6E6E6 = Color(0xFFE6E6E6);
const kFFF4FFFA = Color(0xFFF4FFFA);
const kFFB8B8B8 = Color(0xFFB8B8B8);
const kFFE7E7E7 = Color(0xFFE7E7E7);
const kFF9C9C9C = Color(0xFF9C9C9C);
const kTransparent = Colors.transparent;

const String girlAndDog = 'assets/icon/girl.png';
const String dog = 'assets/icon/bottomdog.png';
const String walkWithDog = 'assets/icon/1.png';
const String selfeWithDog = 'assets/icon/3.png';
const String dogAvtar = 'assets/image/dog.jpg';
const String name = 'assets/icon/Profile.png';
const String userPassword = 'assets/icon/Lock.png';
const String eye = 'assets/icon/Show.png';
const String userName = 'assets/icon/user-square.png';
const String location = 'assets/icon/Location.png';
const String phone = 'assets/icon/phone.png';
const String email = 'assets/icon/email.png';
const String filter = 'assets/icon/Filter.png';
const String search = 'assets/icon/Search.png';
const String bag = 'assets/icon/Work.png';
const String heart = 'assets/icon/heart.png';
const String calendar = 'assets/icon/Calendar.png';
